version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production